/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_apple_ndktest_NDKManager */

#ifndef _Included_com_example_apple_ndktest_NDKManager
#define _Included_com_example_apple_ndktest_NDKManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_apple_ndktest_NDKManager
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_apple_ndktest_NDKManager_getName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
